import type { Product } from "./catalog";

type CatalogueProduct = Omit<
  Product,
  "supplierCostKobo" | "rating" | "reviewCount" | "isFeatured" | "isPublished" | "isTestData"
> & {
  isFeatured?: boolean;
};

const catalogueProduct = (product: CatalogueProduct): Product => ({
  ...product,
  supplierCostKobo: null,
  rating: 47,
  reviewCount: 1,
  isFeatured: product.isFeatured ?? false,
  isPublished: true,
  isTestData: true,
});

export const expandedSeedProducts: Product[] = [
  catalogueProduct({
    name: "VoltGo 20,000mAh Fast-Charge Power Bank",
    slug: "voltgo-20000mah-fast-charge-power-bank",
    sku: "REN-PHN-010",
    categorySlug: "phones-tablets",
    shortDescription: "Dependable high-capacity power for phones, tablets and daily travel.",
    description: "A slim 20,000mAh portable charger with fast USB-C charging, dual-device output and a clear battery indicator for commutes, workdays and travel.",
    priceKobo: 1890000,
    compareAtKobo: 2190000,
    imageUrl: "/products/catalog/voltgo-20000mah-fast-charge-power-bank.webp",
    stock: 28,
    badge: "Mobile essential",
    variants: ["Graphite", "Sand"],
    isFeatured: true,
  }),
  catalogueProduct({
    name: "Canvas 10.1-inch Everyday Tablet",
    slug: "canvas-10-inch-everyday-tablet",
    sku: "REN-PHN-011",
    categorySlug: "phones-tablets",
    shortDescription: "A bright, portable screen for learning, streaming and everyday tasks.",
    description: "A versatile 10.1-inch tablet with generous storage, Wi-Fi connectivity and a protective folio for reading, entertainment and light productivity.",
    priceKobo: 12990000,
    compareAtKobo: 14990000,
    imageUrl: "/products/catalog/canvas-10-inch-everyday-tablet.webp",
    stock: 14,
    badge: "Everyday tech",
    variants: ["64GB Wi-Fi", "128GB Wi-Fi"],
  }),
  catalogueProduct({
    name: "WorkLite 15.6-inch Productivity Laptop",
    slug: "worklite-15-inch-productivity-laptop",
    sku: "REN-COM-012",
    categorySlug: "computing",
    shortDescription: "A capable full-size laptop for work, study and everyday browsing.",
    description: "A clean 15.6-inch notebook with a comfortable keyboard, responsive solid-state storage and the everyday performance needed for documents, calls and web work.",
    priceKobo: 41990000,
    compareAtKobo: 45990000,
    imageUrl: "/products/catalog/worklite-15-inch-productivity-laptop.webp",
    stock: 9,
    badge: "Work ready",
    variants: ["8GB / 256GB", "16GB / 512GB"],
    isFeatured: true,
  }),
  catalogueProduct({
    name: "DeskFlow Wireless Keyboard & Mouse Set",
    slug: "deskflow-wireless-keyboard-mouse-set",
    sku: "REN-COM-013",
    categorySlug: "computing",
    shortDescription: "A quiet, coordinated desktop set for focused work.",
    description: "A low-profile wireless keyboard and precise optical mouse that share one compact receiver, keeping home and office desks calm and uncluttered.",
    priceKobo: 2990000,
    compareAtKobo: 3490000,
    imageUrl: "/products/catalog/deskflow-wireless-keyboard-mouse-set.webp",
    stock: 25,
    badge: "Desk upgrade",
    variants: ["Warm White", "Charcoal"],
  }),
  catalogueProduct({
    name: "Vista 43-inch Smart Television",
    slug: "vista-43-inch-smart-television",
    sku: "REN-ELC-014",
    categorySlug: "electronics",
    shortDescription: "Crisp home entertainment with streaming-ready convenience.",
    description: "A slim 43-inch smart television with a vivid full-HD picture, built-in streaming support and multiple ports for consoles, decoders and sound systems.",
    priceKobo: 21990000,
    compareAtKobo: 24990000,
    imageUrl: "/products/catalog/vista-43-inch-smart-television.webp",
    stock: 10,
    badge: "Home cinema",
    variants: ["43-inch"],
    isFeatured: true,
  }),
  catalogueProduct({
    name: "Pulse Mini Bluetooth Speaker",
    slug: "pulse-mini-bluetooth-speaker",
    sku: "REN-ELC-015",
    categorySlug: "electronics",
    shortDescription: "Room-filling portable sound in a compact, easy-carry form.",
    description: "A rechargeable wireless speaker with balanced sound, simple controls and a durable woven exterior for listening at home or on the move.",
    priceKobo: 3290000,
    compareAtKobo: 3890000,
    imageUrl: "/products/catalog/pulse-mini-bluetooth-speaker.webp",
    stock: 22,
    badge: "Portable audio",
    variants: ["Terracotta", "Graphite"],
  }),
  catalogueProduct({
    name: "Form Ergonomic Office Chair",
    slug: "form-ergonomic-office-chair",
    sku: "REN-HOM-016",
    categorySlug: "home-office",
    shortDescription: "Supportive adjustability for more comfortable workdays.",
    description: "An ergonomic task chair with breathable back support, height adjustment and a stable wheeled base for home offices, studios and study spaces.",
    priceKobo: 18500000,
    compareAtKobo: 21500000,
    imageUrl: "/products/catalog/form-ergonomic-office-chair.webp",
    stock: 12,
    badge: "Workspace edit",
    variants: ["Charcoal", "Warm Grey"],
  }),
  catalogueProduct({
    name: "Glow Adjustable LED Desk Lamp",
    slug: "glow-adjustable-led-desk-lamp",
    sku: "REN-HOM-017",
    categorySlug: "home-office",
    shortDescription: "Focused, adjustable light for reading, study and detailed work.",
    description: "A sculptural LED desk lamp with a flexible head, multiple brightness levels and a compact base suited to bedside tables and workspaces.",
    priceKobo: 2850000,
    compareAtKobo: 3290000,
    imageUrl: "/products/catalog/glow-adjustable-led-desk-lamp.webp",
    stock: 21,
    badge: "Workspace glow",
    variants: ["Ivory", "Clay"],
  }),
  catalogueProduct({
    name: "Crisp 7L Digital Air Fryer",
    slug: "crisp-7l-digital-air-fryer",
    sku: "REN-APP-018",
    categorySlug: "appliances",
    shortDescription: "Generous-capacity air frying for quick family meals.",
    description: "A 7-litre digital air fryer with adjustable time and temperature, a removable nonstick basket and ample room for everyday family cooking.",
    priceKobo: 4890000,
    compareAtKobo: 5590000,
    imageUrl: "/products/catalog/crisp-7l-digital-air-fryer.webp",
    stock: 17,
    badge: "Kitchen favourite",
    variants: ["7L Black", "7L Cream"],
    isFeatured: true,
  }),
  catalogueProduct({
    name: "SteamEase 2L Electric Kettle",
    slug: "steamease-2l-electric-kettle",
    sku: "REN-APP-019",
    categorySlug: "appliances",
    shortDescription: "Fast everyday boiling with a clean, practical design.",
    description: "A 2-litre electric kettle with automatic shut-off, boil-dry protection and an easy-pour handle for tea, coffee and meal preparation.",
    priceKobo: 1390000,
    compareAtKobo: 1650000,
    imageUrl: "/products/catalog/steamease-2l-electric-kettle.webp",
    stock: 33,
    badge: "Everyday value",
    variants: ["Stainless", "Cream"],
  }),
  catalogueProduct({
    name: "Meridian Unisex Everyday Watch",
    slug: "meridian-unisex-everyday-watch",
    sku: "REN-FAS-020",
    categorySlug: "fashion",
    shortDescription: "A timeless, minimal watch made for everyday styling.",
    description: "A refined analogue wristwatch with a slim case, clear dial and adjustable strap that moves easily between work, weekends and occasions.",
    priceKobo: 2490000,
    compareAtKobo: 2990000,
    imageUrl: "/products/catalog/meridian-unisex-everyday-watch.webp",
    stock: 19,
    badge: "Style essential",
    variants: ["Espresso Leather", "Silver Mesh"],
  }),
  catalogueProduct({
    name: "Solace Cross-Strap Sandals",
    slug: "solace-cross-strap-sandals",
    sku: "REN-FAS-021",
    categorySlug: "fashion",
    shortDescription: "Easy neutral sandals for polished warm-weather comfort.",
    description: "A versatile pair of cross-strap sandals with a softly cushioned footbed and a clean silhouette that works across casual and dressier looks.",
    priceKobo: 2950000,
    compareAtKobo: 3450000,
    imageUrl: "/products/catalog/solace-cross-strap-sandals.webp",
    stock: 26,
    badge: "Weekend edit",
    variants: ["EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42"],
  }),
  catalogueProduct({
    name: "Dew Daily Body Lotion 400ml",
    slug: "dew-daily-body-lotion-400ml",
    sku: "REN-BEA-022",
    categorySlug: "health-beauty",
    shortDescription: "Lightweight daily moisture with a smooth, comfortable finish.",
    description: "An easy-spread body lotion in a practical pump bottle, designed to leave skin feeling soft and comfortable without a heavy residue.",
    priceKobo: 1190000,
    compareAtKobo: 1390000,
    imageUrl: "/products/catalog/dew-daily-body-lotion-400ml.webp",
    stock: 34,
    badge: "Daily care",
    variants: ["400ml"],
  }),
  catalogueProduct({
    name: "TrimPro Rechargeable Hair Clipper",
    slug: "trimpro-rechargeable-hair-clipper",
    sku: "REN-BEA-023",
    categorySlug: "health-beauty",
    shortDescription: "Cordless precision grooming with useful guide attachments.",
    description: "A rechargeable hair clipper with multiple guide combs, a comfortable grip and a cleaning brush for convenient home grooming and maintenance.",
    priceKobo: 1890000,
    compareAtKobo: 2250000,
    imageUrl: "/products/catalog/trimpro-rechargeable-hair-clipper.webp",
    stock: 27,
    badge: "Grooming pick",
    variants: ["Graphite"],
  }),
  catalogueProduct({
    name: "LearnBright School Lunch Box Set",
    slug: "learnbright-school-lunch-box-set",
    sku: "REN-KID-024",
    categorySlug: "kids-corner",
    shortDescription: "A cheerful, compartmented set for tidy school-day meals.",
    description: "A reusable lunch box and bottle set with practical compartments, secure closures and an easy-carry shape for school and day trips.",
    priceKobo: 950000,
    compareAtKobo: 1150000,
    imageUrl: "/products/catalog/learnbright-school-lunch-box-set.webp",
    stock: 35,
    badge: "School day",
    variants: ["Coral", "Teal"],
  }),
  catalogueProduct({
    name: "LittleMaker Creative Art Set",
    slug: "littlemaker-creative-art-set",
    sku: "REN-KID-025",
    categorySlug: "kids-corner",
    shortDescription: "Colourful creative tools for drawing, colouring and making.",
    description: "A neatly organised children’s art kit with washable colouring tools, paper essentials and a portable case for imaginative projects at home or school.",
    priceKobo: 1490000,
    compareAtKobo: 1790000,
    imageUrl: "/products/catalog/littlemaker-creative-art-set.webp",
    stock: 29,
    badge: "Creative play",
    variants: ["48-piece set"],
  }),
  catalogueProduct({
    name: "CloudSoft Newborn Diaper Pack",
    slug: "cloudsoft-newborn-diaper-pack",
    sku: "REN-BAB-026",
    categorySlug: "baby-products",
    shortDescription: "Soft, breathable everyday protection for newborn comfort.",
    description: "A practical newborn diaper pack with a soft lining, secure tabs and a flexible fit designed for comfortable everyday care.",
    priceKobo: 1790000,
    compareAtKobo: 2050000,
    imageUrl: "/products/catalog/cloudsoft-newborn-diaper-pack.webp",
    stock: 30,
    badge: "Baby essential",
    variants: ["Newborn", "Size 1", "Size 2"],
  }),
  catalogueProduct({
    name: "NestCarry Convertible Baby Diaper Bag",
    slug: "nestcarry-convertible-baby-diaper-bag",
    sku: "REN-BAB-027",
    categorySlug: "baby-products",
    shortDescription: "Organised, hands-free storage for feeds, changes and travel.",
    description: "A roomy convertible diaper backpack with insulated bottle pockets, organised compartments and comfortable straps for everyday family outings.",
    priceKobo: 3290000,
    compareAtKobo: 3890000,
    imageUrl: "/products/catalog/nestcarry-convertible-baby-diaper-bag.webp",
    stock: 18,
    badge: "Parent favourite",
    variants: ["Sand", "Charcoal"],
  }),
  catalogueProduct({
    name: "FlexFit Resistance Bands Set",
    slug: "flexfit-resistance-bands-set",
    sku: "REN-SPT-028",
    categorySlug: "sporting-goods",
    shortDescription: "Five versatile resistance levels for training almost anywhere.",
    description: "A compact set of colour-coded loop resistance bands with varied strengths and a travel pouch for warm-ups, mobility and strength sessions.",
    priceKobo: 1350000,
    compareAtKobo: 1590000,
    imageUrl: "/products/catalog/flexfit-resistance-bands-set.webp",
    stock: 32,
    badge: "Home fitness",
    variants: ["5-band set"],
  }),
  catalogueProduct({
    name: "CoreBalance Yoga Mat",
    slug: "corebalance-yoga-mat",
    sku: "REN-SPT-029",
    categorySlug: "sporting-goods",
    shortDescription: "Comfortable cushioning and grip for movement and stretching.",
    description: "A supportive exercise mat with a textured non-slip surface and carrying strap for yoga, Pilates, stretching and floor workouts.",
    priceKobo: 1890000,
    compareAtKobo: 2250000,
    imageUrl: "/products/catalog/corebalance-yoga-mat.webp",
    stock: 24,
    badge: "Studio essential",
    variants: ["Clay", "Sage", "Graphite"],
  }),
  catalogueProduct({
    name: "AeroPad Wireless Game Controller",
    slug: "aeropad-wireless-game-controller",
    sku: "REN-GAM-030",
    categorySlug: "gaming",
    shortDescription: "Responsive wireless control for comfortable extended play.",
    description: "A rechargeable game controller with textured grips, familiar controls and low-latency wireless pairing for compatible consoles, computers and mobile devices.",
    priceKobo: 2690000,
    compareAtKobo: 3150000,
    imageUrl: "/products/catalog/aeropad-wireless-game-controller.webp",
    stock: 23,
    badge: "Player pick",
    variants: ["Charcoal", "Ivory"],
    isFeatured: true,
  }),
  catalogueProduct({
    name: "NovaPlay Compact Retro Game Console",
    slug: "novaplay-compact-retro-game-console",
    sku: "REN-GAM-031",
    categorySlug: "gaming",
    shortDescription: "A compact living-room console for easy pick-up-and-play fun.",
    description: "A space-saving game console with wireless controllers and simple television connectivity, designed for casual group and family play.",
    priceKobo: 5990000,
    compareAtKobo: 6990000,
    imageUrl: "/products/catalog/novaplay-compact-retro-game-console.webp",
    stock: 13,
    badge: "Game night",
    variants: ["Two-controller set"],
  }),
  catalogueProduct({
    name: "GoldenGrain Premium Rice 5kg",
    slug: "goldengrain-premium-rice-5kg",
    sku: "REN-GRO-032",
    categorySlug: "groceries",
    shortDescription: "Versatile long-grain rice for dependable everyday meals.",
    description: "A 5kg pantry pack of carefully selected long-grain rice suitable for jollof, fried rice, stews and everyday family cooking.",
    priceKobo: 3950000,
    compareAtKobo: 4290000,
    imageUrl: "/products/catalog/goldengrain-premium-rice-5kg.webp",
    stock: 40,
    badge: "Pantry staple",
    variants: ["5kg"],
  }),
  catalogueProduct({
    name: "PantryPack Breakfast Oats 1kg",
    slug: "pantrypack-breakfast-oats-1kg",
    sku: "REN-GRO-033",
    categorySlug: "groceries",
    shortDescription: "Wholesome rolled oats for quick breakfasts and baking.",
    description: "A resealable 1kg pack of rolled oats for porridge, overnight oats, smoothies and home baking.",
    priceKobo: 890000,
    compareAtKobo: 1050000,
    imageUrl: "/products/catalog/pantrypack-breakfast-oats-1kg.webp",
    stock: 44,
    badge: "Breakfast choice",
    variants: ["1kg"],
  }),
  catalogueProduct({
    name: "GreenGrip 5-piece Garden Tool Set",
    slug: "greengrip-5-piece-garden-tool-set",
    sku: "REN-GAR-034",
    categorySlug: "garden-outdoors",
    shortDescription: "A practical hand-tool set for planting and everyday garden care.",
    description: "A five-piece gardening set with a trowel, cultivator, transplanter, pruning shears and gloves for pots, beds and small outdoor spaces.",
    priceKobo: 2490000,
    compareAtKobo: 2890000,
    imageUrl: "/products/catalog/greengrip-5-piece-garden-tool-set.webp",
    stock: 20,
    badge: "Garden ready",
    variants: ["5-piece set"],
  }),
  catalogueProduct({
    name: "SolarGlow Outdoor Security Light",
    slug: "solarglow-outdoor-security-light",
    sku: "REN-GAR-035",
    categorySlug: "garden-outdoors",
    shortDescription: "Motion-responsive solar lighting for paths and entrances.",
    description: "A weather-ready outdoor solar light with motion sensing, a wide illumination area and cable-free installation for walls, gates and walkways.",
    priceKobo: 1990000,
    compareAtKobo: 2350000,
    imageUrl: "/products/catalog/solarglow-outdoor-security-light.webp",
    stock: 31,
    badge: "Outdoor essential",
    variants: ["Single", "Pair"],
  }),
  catalogueProduct({
    name: "RoadReady Portable Tyre Inflator",
    slug: "roadready-portable-tyre-inflator",
    sku: "REN-AUT-036",
    categorySlug: "automobile",
    shortDescription: "Compact cordless inflation for tyres and roadside readiness.",
    description: "A rechargeable portable inflator with a clear pressure display, preset shut-off and useful adapters for car tyres, bicycles and sports equipment.",
    priceKobo: 2890000,
    compareAtKobo: 3390000,
    imageUrl: "/products/catalog/roadready-portable-tyre-inflator.webp",
    stock: 19,
    badge: "Road essential",
    variants: ["Cordless kit"],
  }),
  catalogueProduct({
    name: "DriveView Dual-Lens Dash Camera",
    slug: "driveview-dual-lens-dash-camera",
    sku: "REN-AUT-037",
    categorySlug: "automobile",
    shortDescription: "Front-and-cabin recording for clearer everyday journeys.",
    description: "A compact dual-lens dashboard camera with loop recording, night support and a wide viewing angle for helpful trip documentation.",
    priceKobo: 6590000,
    compareAtKobo: 7490000,
    imageUrl: "/products/catalog/driveview-dual-lens-dash-camera.webp",
    stock: 14,
    badge: "Drive smarter",
    variants: ["Camera only", "Camera + 64GB card"],
  }),
  catalogueProduct({
    name: "BuildMind 80-piece Wooden Block Set",
    slug: "buildmind-80-piece-wooden-block-set",
    sku: "REN-TOY-038",
    categorySlug: "toys-games",
    shortDescription: "Open-ended shapes and colours for imaginative building play.",
    description: "An 80-piece wooden building set with varied shapes, calm colours and a storage tub for creative construction, sorting and collaborative play.",
    priceKobo: 2290000,
    compareAtKobo: 2690000,
    imageUrl: "/products/catalog/buildmind-80-piece-wooden-block-set.webp",
    stock: 22,
    badge: "Creative play",
    variants: ["80-piece set"],
  }),
  catalogueProduct({
    name: "Family Night Strategy Board Game",
    slug: "family-night-strategy-board-game",
    sku: "REN-TOY-039",
    categorySlug: "toys-games",
    shortDescription: "Easy-to-learn tabletop strategy for friends and families.",
    description: "A colourful, replayable strategy game with tactile pieces and straightforward rules designed for relaxed game nights and group play.",
    priceKobo: 1850000,
    compareAtKobo: 2190000,
    imageUrl: "/products/catalog/family-night-strategy-board-game.webp",
    stock: 25,
    badge: "Game night",
    variants: ["2–4 players"],
  }),
  catalogueProduct({
    name: "MeasurePro Digital Multimeter",
    slug: "measurepro-digital-multimeter",
    sku: "REN-IND-040",
    categorySlug: "industrial-scientific",
    shortDescription: "A clear, compact meter for routine electrical measurement.",
    description: "A handheld digital multimeter with a large display, protective casing and test leads for common voltage, current, resistance and continuity checks.",
    priceKobo: 3490000,
    compareAtKobo: 3990000,
    imageUrl: "/products/catalog/measurepro-digital-multimeter.webp",
    stock: 17,
    badge: "Workshop tool",
    variants: ["Meter + leads"],
  }),
  catalogueProduct({
    name: "SafeSight Protective Goggles & Work Gloves Set",
    slug: "safesight-protective-goggles-work-gloves-set",
    sku: "REN-IND-041",
    categorySlug: "industrial-scientific",
    shortDescription: "Practical eye and hand protection for everyday workshop tasks.",
    description: "A coordinated safety set with clear impact-resistant goggles and textured work gloves for home projects, maintenance and light workshop use.",
    priceKobo: 1690000,
    compareAtKobo: 1990000,
    imageUrl: "/products/catalog/safesight-protective-goggles-work-gloves-set.webp",
    stock: 28,
    badge: "Safety first",
    variants: ["Medium", "Large", "Extra Large"],
  }),
  catalogueProduct({
    name: "Modern African Fiction Book Collection",
    slug: "modern-african-fiction-book-collection",
    sku: "REN-BMM-042",
    categorySlug: "books-movies-music",
    shortDescription: "A considered set of contemporary stories for a home reading shelf.",
    description: "A curated multi-book fiction collection spanning family, ambition, memory and modern African life, presented as an inviting reading bundle.",
    priceKobo: 2790000,
    compareAtKobo: 3290000,
    imageUrl: "/products/catalog/modern-african-fiction-book-collection.webp",
    stock: 16,
    badge: "Editor’s shelf",
    variants: ["5-book collection"],
  }),
  catalogueProduct({
    name: "Weekend Movie Night Disc Collection",
    slug: "weekend-movie-night-disc-collection",
    sku: "REN-BMM-043",
    categorySlug: "books-movies-music",
    shortDescription: "A varied film collection for relaxed nights at home.",
    description: "A curated disc bundle featuring a balanced mix of drama, comedy and adventure in simple archival cases for a versatile home movie shelf.",
    priceKobo: 3190000,
    compareAtKobo: 3690000,
    imageUrl: "/products/catalog/weekend-movie-night-disc-collection.webp",
    stock: 12,
    badge: "Movie night",
    variants: ["8-disc collection"],
  }),
  catalogueProduct({
    name: "Tempo 61-key Electronic Keyboard",
    slug: "tempo-61-key-electronic-keyboard",
    sku: "REN-MUS-044",
    categorySlug: "musical-instruments",
    shortDescription: "An approachable full-width keyboard for learning and creating.",
    description: "A 61-key electronic keyboard with built-in sounds, practice functions, a music rest and simple connectivity for lessons, rehearsals and home creativity.",
    priceKobo: 11990000,
    compareAtKobo: 13790000,
    imageUrl: "/products/catalog/tempo-61-key-electronic-keyboard.webp",
    stock: 8,
    badge: "Start playing",
    variants: ["Keyboard only", "Keyboard + stand"],
  }),
  catalogueProduct({
    name: "EmberTone Acoustic Guitar",
    slug: "embertone-acoustic-guitar",
    sku: "REN-MUS-045",
    categorySlug: "musical-instruments",
    shortDescription: "A warm, balanced acoustic guitar for practice and performance.",
    description: "A full-size steel-string acoustic guitar with a comfortable neck, natural finish and padded carry bag for learners, writers and casual performers.",
    priceKobo: 8990000,
    compareAtKobo: 10490000,
    imageUrl: "/products/catalog/embertone-acoustic-guitar.webp",
    stock: 11,
    badge: "Creative pick",
    variants: ["Natural", "Warm Walnut"],
  }),
];
