"use client";
import { FormEvent, useState } from "react";
import { usePathname } from "next/navigation";
type Message = { role: "assistant" | "user"; text: string };
export function ProductAssistant() {
  const pathname = usePathname(); const slug = pathname.startsWith("/products/") ? pathname.split("/")[2] : "";
  const [open, setOpen] = useState(false); const [input, setInput] = useState(""); const [loading, setLoading] = useState(false); const [messages, setMessages] = useState<Message[]>([{ role: "assistant", text: slug ? "Hi. Ask me about this product, delivery, availability or returns." : "Hi. I can help you find products and answer questions about delivery, checkout, tracking and returns." }]);
  async function send(event: FormEvent) { event.preventDefault(); const text = input.trim(); if (!text || loading) return; setMessages((items) => [...items, { role: "user", text }]); setInput(""); setLoading(true); try { const response = await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ slug, message: text }) }); const payload = await response.json() as { reply?: string; error?: string }; setMessages((items) => [...items, { role: "assistant", text: payload.reply ?? payload.error ?? "I could not answer that just now." }]); } catch { setMessages((items) => [...items, { role: "assistant", text: "I could not connect just now. Please try again or email support@shoprenova.com.ng." }]); } finally { setLoading(false); } }
  const suggestions = slug ? ["When will it arrive?", "Is it available?", "What is the return policy?"] : ["Help me find a product", "How long is delivery?", "How do I track an order?"];
  return <div className={`product-assistant ${open ? "is-open" : ""}`}><button type="button" className="assistant-launcher" onClick={() => setOpen(!open)} aria-label={open ? "Close product assistant" : "Open product assistant"}><span>✦</span><b>{open ? "Close" : "Ask Renova"}</b></button>{open && <section className="assistant-panel" role="dialog" aria-label="Ask Renova assistant"><header><div><span>✦</span><div><b>Ask Renova</b><small>{slug ? "Using this product’s approved facts" : "Store and shopping assistance"}</small></div></div><button type="button" onClick={() => setOpen(false)} aria-label="Close assistant">×</button></header><div className="assistant-messages" aria-live="polite">{messages.map((message, index) => <p className={message.role} key={index}>{message.text}</p>)}{loading && <p className="assistant">Thinking…</p>}</div>{messages.length < 3 && <div className="assistant-suggestions">{suggestions.map((item) => <button type="button" key={item} onClick={() => setInput(item)}>{item}</button>)}</div>}<form onSubmit={send}><input autoFocus value={input} onChange={(e) => setInput(e.target.value)} maxLength={600} placeholder={slug ? "Ask about this product…" : "Ask Renova anything about the store…"}/><button type="submit" disabled={loading || !input.trim()}>{loading ? "…" : "Send"}</button></form><footer>AI can make mistakes. Product facts and checkout details remain the source of truth.</footer></section>}</div>;
}
